### ISSUE TITLE
[Request]: Wii input - Change GPIO pins

### ISSUE THREAD

**Issue by j-d-rutherford** [Santroller/guitar-configurator#15] opened 2023-11-17 14:16 UTC
### Please describe your request.

I purchased a Waveshare RP2040Zero that has the GP18 and 19 pins as pads instead of edge connections/header pins. 

https://www.waveshare.com/w/A6Y79bcq/Kdy80nYY.php?f=RP2040-Zero-details-7.jpg&width=559

Can you please add support for other GPIO pins for boards that do not have 18/19 accessible?

### What operating system are you using?

Windows 10

### What microcontroller are you making a request for?

pi pico

### How will the microcontroller be programed for this request?

Wii

**Comment by sanjay900** [comment] 2023-11-17 21:27
Duplicate of https://github.com/Santroller/Santroller/issues/12

**Closed as completed by sanjay900** 2023-11-17 21:27 UTC
